### ISSUE TITLE
Create helper method to toggle profile section

### ISSUE THREAD

**Issue by elefeint** [googleinterns/step90-2020#22]
These two lines repeat a lot:
```
document.getElementById("profile-section").style.display = "block";
document.getElementById("no-profile").style.display = "none";
```

I'd recommend adding a helper method `toggleProfile(state)` that would take a boolean flag as a parameter and set display in one section to "block" and the other to "none".

**Comment by jsheng112** [comment]
Addressed in a previous PR.
