### ISSUE TITLE
validate IAP headers

### ISSUE THREAD

**Issue by jsheng112** [googleinterns/step90-2020#48]

**Comment by elefeint** [comment]
This can be done for you automatically by the `spring-cloud-gcp-starter-security-iap`dependency.

Here is a sample demonstrating : 
https://github.com/spring-cloud/spring-cloud-gcp/tree/4b1f2c8ad146390a08ba96373806f775aa587f20/spring-cloud-gcp-samples/spring-cloud-gcp-security-iap-sample
