### ISSUE TITLE
Re-enable Event entity's ability to load Organization

### ISSUE THREAD

**Issue by elefeint** [googleinterns/step90-2020#62]
@jsheng112 ran into a circular serialization issue (an Organization contains Events, which in turn contain Organizations). We worked around it with `com.fasterxml.jackson.annotation.JsonIgnore` annotation, which works great for the organization page. But this will remove organization information from the event page, so something more customizable needs to be done.

**Comment by elefeint** [comment]
`@JsonManagedReference` and `@JsonBackReference` should work better than `JsonIgnore`.

**Comment by jsheng112** [comment]
Addressed in PR #95
